### ISSUE TITLE
When testing the addition of the SMR some things do not seem to go as planned

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etm-esdl#103]
After adding the SMR I tested the export_esdl function (including a minimal & maximum scenario) but no power or range seems to be added. Do you have any idea why @Roos?

I have deleted the range attribute & set the power attribute to 0.0 for the smr in the file Projects/Active/537 Multi Modelling voor Integrale Besluitvorming (RVO)/03 Project/ESDL/Macro/**MACRO 6.1.esdl** in order to test it. 

branch: **smr**

**Comment by redekok** [comment]
Is this issue still relevant @Charlottevm ?
