### ISSUE TITLE
Some data does not get into the ESDL properly

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etm-esdl#115]
There are a few data-points that do not seem to get through to the ESDL properly:

1. No range is added for batteries and nuclear powerplants (ESDL export -> `esdl:Battery` -> `esdl:RangedConstraint` should have different/set `minValue` and `maxValue`. Same for `esdl:PowerPlant`, type `URANIUM`). _Find out why_.
2. Max / Min discharge rate for baterries does not change based on scenario (ESDL export -> `esdl:Battery` -> `maxChargeRate` en `maxDischargeRate`). Should this be the case? If so, _find out why its not exported_.
3. Planttype for nuclear powerplant seems to be removed in the output. _Find out why_.

For testing purposes I am using: 

- the `export` function on the beta server
- the file .../537 Multi Modelling voor Integrale Besluitvorming (RVO)/03 Project/ESDL/Demo/create scenario/**MACRO_input.esdl**, 
- and the scenario numbers: `2493258` (min), `2493273` (max)

**Comment by noracato** [comment]
Point 4 is a possible engine issue. Should be picked up separately (with @mabijkerk)

**Comment by Charlottevm** [comment]
It was a mistake in the etm-esdl app after all, the query was wrong, so no need to look into it @noracato , @mabijkerk !

**Comment by noracato** [comment]
Ok, I'll close it then!
