### ISSUE TITLE
Add filter options to all endpoints (+/- 0.5 day)

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etm-esdl#79]
In many (multi-model) cases you want to have the option of choosing what to add/change in the ESDL based on an ETM scenario or read from the ESDL to create a scenario. This means we need to implement a filter option for different assets, kpi's, carriers etc. 

**Format**
Simple list containing all assets, kpi's or carriers that should be added/read (per API). For assets the filter can be based on the esdl asset, for kpi's and carriers it can be based on the name we give that carrier/kpi. If no list is provided, the app refers back to adding/changing/reading all possible options presented within an esdl.

**Comment by noracato** [comment]
After merging #84 we have a filter for assets that is only added to the `export` API.
Next steps are:
- [ ] Attach this filter to the `create` and the `create_with_context` API's
- [ ] Expand this filter to also be able to filter KPIs
