### ISSUE TITLE
Update create_with_context

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etm-esdl#82]
The create_with_context should be more standardized to be able to read different ESDL's. Goal is to be able to read the ESDL's provided in the micro-case, see \Projects/Active/537 Multi Modelling voor Integrale Besluitvorming (RVO)/03 Project/ESDL/Micro/EPS - Tholen Welgelegen (5) (--> 'pand_huidig' & 'pand_scenario')

1. Make a plan for **technical improvements** to this endpoint in order to standardise this endpoint (aka remove all (hardcoded) gridmaster 'hacks/descriptions'), execute if you need less then 0.5 day, otherwise discuss
2. Make a list of everything that needs to be added to the asset list / mapping / parsers in ESDL to be able to read the ESDL provided by the micro-use case, discuss / assign at will

**Comment by noracato** [comment]
The ESDLs you mentioned are missing a date instance, that's mainly why they cannot be parsed by the `create_with_context`.
